### ISSUE TITLE
Convert all library to Typescript

### ISSUE THREAD

**Issue by Elius94** [Elius94/console-gui-tools#35]

**Comment by lather205** [comment]
Hi, I just say this issue. I actually had to convert my project from CJS to ESM when I installed your library. Does converting it all to Typescript mean that my program will break again if it is not converted back?

**Comment by Elius94** [comment]
hi, I have opened a new issue for this currently the project is compatible only with ESM and not with CommonJS (to compile it as commonjs just change the target on the taconfig.json file of the library and recompile with tsc.
However, I know that there are methods to do this automatically when installing the library in a project.
I will try to add this feature shortly.

**Comment by Elius94** [comment]
hi, I have opened a new issue for this currently the project is compatible only with ESM and not with CommonJS (to compile it as commonjs just change the target on the taconfig.json file of the library and recompile with tsc.
However, I know that there are methods to do this automatically when installing the library in a project.
I will try to add this feature shortly.
