### ISSUE TITLE
[Bug]: OptionPopup - selected prop = "" is considered undefined

### ISSUE THREAD

**Issue by Elius94** [Elius94/console-gui-tools#68]
### What happened?

If you define a OptionPopup with selected: "", it throw a error considering selected undefined.

### What should have happened?

It should allow to set it to empty string

### Code

```js
new OptionPopup({
  id: "testBox",
  title: "title",
  options: opts,
  selected: ""
})
```

### Library Version

3.0.4

### Node Version

19.3

### What operating system are you using?

Windows

### Terminal

Windows Terminal

### Interest to fix the bug

- [X] I would like to fix this bug!

**Comment by Compositr** [comment]
Did some further testing, anything that is falsy will throw an error because the if statement just uses a `!` rather than a strict test for `null | undefined`

Bugged code

https://github.com/elius94/console-gui-tools/blob/main/src/components/widgets/OptionPopup.ts#L79

**Comment by Elius94** [comment]
You are right! In addition I think that empty strings in node are considered false if you test them.
Tnaks

**Comment by Compositr** [comment]
Opening a PR to address it if you don't mind. #69
