### ISSUE TITLE
[Feature]: Popups Offset

### ISSUE THREAD

**Issue by hygameo** [Elius94/console-gui-tools#73]
### What do you want?

I want to offset the popups

### Why do you want it?

I think it'll be more convenient to have the pop ups offset feature

### How do you implement it?

IDK...

P/s: Sorry alot for my lack of knowledge and bad English

### Are you interested in developing this feature?

- [ ] Yes, I am interested in developing this feature
- [X] No, I am not interested in developing this feature

**Comment by Elius94** [comment]
Hi! what do you mean for "offset"? Offset from what?

**Comment by hygameo** [comment]
When i create a new ButtonPopup class it shows up in the center of the terminal window. So is there any way to offset it from the center of that terminal window? Sorry if it's my fault for not reading the documents carefully and thank you for your reply!

**Comment by Elius94** [comment]
https://github.com/Elius94/console-gui-tools/blob/main/docs/OptionPopup.md

x and y ;)
