### ISSUE TITLE
[Bug]: commonjs script can't import this library

### ISSUE THREAD

**Issue by kamenomi-dev** [Elius94/console-gui-tools#92]
### What happened?

I can't import the console-gui-tools library via commonjs

### What should have happened?

[codesandbox.io](https://codesandbox.io/p/devbox/romantic-chatterjee-j9k46w?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyxcopf300063j6kwxyozti1%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyxcopf200023j6koudnpgi0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyxcopf200043j6kgsgryzqq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyxcopf200053j6k5nnzj59h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyxcopf200023j6koudnpgi0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyxcopf100013j6k28wz5mxd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clyxcopf200023j6koudnpgi0%2522%252C%2522activeTabId%2522%253A%2522clyxcopf100013j6k28wz5mxd%2522%257D%252C%2522clyxcopf200053j6k5nnzj59h%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clyxcopf200053j6k5nnzj59h%2522%257D%252C%2522clyxcopf200043j6kgsgryzqq%2522%253A%257B%2522id%2522%253A%2522clyxcopf200043j6kgsgryzqq%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyxcopf200033j6krn2mtwqm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clyxcqime005q3j6kpkf25dfy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clyxcqjbl001tdag645sc9my7%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clyxcqime005q3j6kpkf25dfy%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
See package.json:
`
{
    "name": "console-gui-tools",
    "version": "3.7.0",
    "description": "A simple library to draw option menu, text popup or other widgets and layout on a Node.js console.",
    "main": "dist/esm/ConsoleGui.mjs",
    "types": "dist/types/ConsoleGui.d.ts",
    "module": "dist/esm/ConsoleGui.mjs",
    "type": "module", // Here will cause it.
    "exports": {
        ".": {
            "types": "./dist/types/ConsoleGui.d.ts",
            "require": "./dist/cjs/ConsoleGui.cjs",
            "import": "./dist/esm/ConsoleGui.mjs"
        }
    },
    "files": [
        "dist/"
    ],
    "scripts": {
        "lint": "eslint ./src/ --ext .ts",
        "build": "node ./esbuild.js",
        "prepare": "npm run build",
        "test": "npm run build && node ./examples/tcp_simulator.mjs",
        "start": "node ./esbuild.js --watch --dev",
        "docs": "node ./docgen.cjs"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/Elius94/console-gui-tools.git"
    },
    "keywords": [
        "console",
        "gui",
        "menu",
        "popup",
        "layout",
        "node",
        "node.js",
        "curses",
        "ncurses",
        "tui",
        "terminal",
        "command-line",
        "logs",
        "terminal-graphics",
        "consoleapp",
        "terminal-colors",
        "terminal-ui"
    ],
    "author": "Elia Lazzari",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/Elius94/console-gui-tools/issues"
    },
    "homepage": "https://github.com/Elius94/console-gui-tools#readme",
    "dependencies": {
        "chalk": "^5.2.0"
    },
    "devDependencies": {
        "@babel/cli": "^7.20.7",
        "@babel/core": "^7.20.12",
        "@babel/plugin-proposal-class-properties": "^7.18.6",
        "@babel/plugin-proposal-object-rest-spread": "^7.20.7",
        "@babel/preset-env": "^7.20.2",
        "@babel/preset-typescript": "^7.18.6",
        "@types/node": "^18.11.18",
        "@typescript-eslint/eslint-plugin": "^5.49.0",
        "@typescript-eslint/parser": "^5.49.0",
        "esbuild": "0.17.4",
        "eslint": "^8.32.0",
        "jsdoc-babel": "^0.5.0",
        "jsdoc-to-markdown": "^8.0.0",
        "typescript": "^4.9.4"
    }
}

`

### Code

```typescript
import * as gui from "console-gui-tools"
```

### Library Version

3.7.0

### Node Version

v22.4.1

### What operating system are you using?

Windows

### Terminal

Windows Powershell

### Interest to fix the bug

- [ ] I would like to fix this bug!

**Comment by Elius94** [comment]
I'm sorry but I can't understand what you mean...
You write "commonjs script can't import this library "
but you are importing the lib as "JS Module (ESM)" 
```js
import * as gui from "console-gui-tools"
```

to import in a CJS project you must use the CJS import pattern:

```js
const { ConsoleManager } = require('console-gui-tools')
```

Please, follow the README.md file!

https://github.com/Elius94/console-gui-tools?tab=readme-ov-file#commonjs-syntax
