### ISSUE TITLE
[Support]: Clean the render without console.clear

### ISSUE THREAD

**Issue by 0xJWLabs** [Elius94/console-gui-tools#94]
### What are you trying to do?

Is there a way to clean the render without console.clear like glow (https://github.com/charmbracelet/glow)?

https://github.com/user-attachments/assets/d493b51b-fea0-4725-b15e-27b8f393c534

### Code

-

### Library Version

3.7.0

### Node Version

20.16.0

### What operating system are you using?

Windows

### Terminal

Wezterm + WSL

**Comment by Elius94** [comment]
Thanks for the issue 🙏
I'll check when I return home after summer holiday.
Have a nice day

**Comment by 0xJWLabs** [comment]
@Elius94 Nice, thanks! Enjoy your holiday!

**Comment by Elius94** [comment]
Hi! I can add console.clear() at the end of the console-gui-tools life, but there are no alternatives I think.
