### ISSUE TITLE
[Bug]: console.log issue with % format specifier

### ISSUE THREAD

**Issue by yasirerkam** [Elius94/console-gui-tools#95]
### What happened?

````ts
console.log("'%s' Dictionaries info:", this.name)
````
It gives the output to the screen as is. i.e.:
`'%s' Dictionaries info:`

### What should have happened?

It should gives the output to the screen as is. i.e.:
`'Italy' Dictionaries info:`

### Extra infos:

By the way, set "overrideConsole: false" already:
````ts
consoleManager = new ConsoleManager({
            title: 'MyTitle', // Title of the console
            overrideConsole: false,
        });
````

If I change the usage to the following it gives the expected result:
````ts
console.log(`'${this.name}' Dictionaries info:`)
````
But since I use %s in most of the project, I want to use it that way. 

Thank you for the your "console-gui-tools" project.

### Library Version

[v3.7.0](https://github.com/Elius94/console-gui-tools/releases/tag/v3.7.0)

### Node Version

v20.17.0

### What operating system are you using?

Windows

### Terminal

[Windows Terminal](https://github.com/microsoft/terminal) with Powershell Core (the last official) as suggested

### Interest to fix the bug

- [ ] I would like to fix this bug!

**Comment by Elius94** [comment]
Hello! 
At the moment, the overridden console.log/error/... are used to show log messages in the log location of the gui and at the moment it can't be used like the standard console log. please input just text, to use string patters you can do like this:
```js
console.log(`Hi, my name is ${name}`)
```
