### ISSUE TITLE
[Bug]: Control construktor doesn't work properly

### ISSUE THREAD

**Issue by MarcinBurczynski** [Elius94/console-gui-tools#96]
### What happened?

When creating a Control object it is permamently draggable even if you specify in the constructor it should be not.

### What should have happened?

the control object should not be draggable 

### Code

const rowControl = new Control({
            id: isFunctionalRow ? `row_${rowID}` : `Nonfunctional_row_${i}`,
            attributes: { x: 1, y: i + 1, width: totalWidth - 8, height: 1 },
            children: widget,
            draggable: false
        });

### Library Version

3.7.0

### Node Version

20.17.0

### What operating system are you using?

Other Linux

### Terminal

zsh

### Interest to fix the bug

- [X] I would like to fix this bug!

**Comment by Elius94** [comment]
Hey! 
you need to set a proper height. if you set 1 you cannot hang to the shape of the control.
try to set 2 or more. 
for example:

```js
const {
  ConsoleManager,
  ConfirmPopup,
  InPageWidgetBuilder,
  Control
} = require("console-gui-tools");

//const si = require("systeminformation");
// si.currentLoad().then((data) => {
//   console.log(JSON.stringify(data));
// });

const opt = {
  title: "SYSTEM INFO", // Title of the console
  enableMouse: true, // Enable mouse support
};
const GUI = new ConsoleManager(opt);

const widget1 = new InPageWidgetBuilder()
widget1.addRow({ text: "┌────────┐", color: "yellow", style: "bold" })
widget1.addRow({ text: "│ START! │", color: "yellow", style: "bold" })
widget1.addRow({ text: "└────────┘", color: "yellow", style: "bold" })

/*const rowControl = */new Control({
  id: "fsd",
  attributes: { x: 80, y: 1, width: 10, height: 3 },
  children: widget1,
  draggable: true,
  visible: true,
});



GUI.on("exit", () => {
  closeApp();
});

GUI.on("keypressed", (key) => {
  switch (key.name) {
    case "q":
      new ConfirmPopup({
        id: "popupQuit",
        title: "Are you sure you want to quit?",
      })
        .show()
        .on("confirm", () => closeApp());
      break;
    default:
      break;
  }
});

const closeApp = () => {
  console.clear();
  process.exit();
};

GUI.refresh();

```

**Comment by Elius94** [comment]
You can put height to 1, but check also the dynamic width.
You can't know if the children is bigger than the Control, the overflow is visible, so you need to check the size better. 
The size is related to the draggable area.
